### PR TITLE
g++ version check only for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ar13pit**

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
Why?

**Comment by ar13pit** [comment]
On Ubuntu 18.04 it works with g++ 7

**Comment by ar13pit** [comment]
Its more of a CUDA thing than Kaldi itself

**Comment by MatthijsBurgh** [comment]
> Its more of a CUDA thing than Kaldi itself

Maybe good to add as a comment

**Comment by ar13pit** [comment]
Done

**Pull request merged**
