### PR TITLE
[python-tensorflow-pip] change version limits

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Merge after https://github.com/tue-robotics/image_recognition/pull/102

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Is the code compatible with any version of Tensorflow?

**Comment by MatthijsBurgh** [comment]
@LoyVanBeek see tue-robotics/image_recognition#102

**Comment by LoyVanBeek** [comment]
So then, it's compatible with both 1 and 2 and 3 in the future? That's what the 'no limits on version' entails.

**Comment by MatthijsBurgh** [comment]
No, it is compatible with all currently released versions

**Pull request merged**
