### PR TITLE
Remove github-cache-credentials

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
not really needed with ssh capabilities and very ugly code.

### CODE REVIEW

**Comment by Timple** [comment]
How do you plan to do the ssh administration on all the robot computers?

**Comment by ar13pit** [comment]
@Timple Will it be a good idea to setup a github account for the AMIGO email ID and either use github tokens or manually add ssh-keys of the robots to that account?

**Comment by MatthijsBurgh** [comment]
This is really off-topic for this PR.

**Comment by MatthijsBurgh** [comment]
@ar13pit @Timple please continue here: https://github.com/tue-robotics/tue-env/issues/367

**Comment by ar13pit** [comment]
In my opinion we should keep this as not all computers we use will have ssh-keys linked to our accounts, for example the public computers in the robotics lab.

**Comment by MatthijsBurgh** [comment]
You can still do it yourself. I don't think anyone is using it at the moment.

**Comment by ar13pit** [comment]
No what I meant is I wouldn't want my ssh-keys setup on every computer I have ever used. I would keep it only on the ones that are mine else I'll have to remove the keys from my account after every use.

**Comment by MatthijsBurgh** [comment]
NO SSH STUFF IN THIS PR.

I am just talking about this function, which isn't really needed anymore (because most people will use ssh). Plus it is very ugly and therefore it needs to be removed. If people want to set git credential cache, they can still google it.

**Pull request merged**
