### PR TITLE
Fix gazebo target on xenial

### PR DESCRIPTION
**Pull request by Rayman**
I think nothing depends on gazebo so this won't break anybody, but I'm trying to use it for https://github.com/Rayman/tue_rosdistro and it doesn't work the way it is now.

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
`gazebo-setup` needs to stay.

For the gazebo target. We should follow rosdistro:
https://github.com/ros/rosdistro/blob/11cebc7a2f2eac7e80191f77d3fd8db725a03e26/rosdep/base.yaml#L929-L953

**Comment by Rayman** [comment]
Only xenial & bionic, or the whole thing?

**Comment by MatthijsBurgh** [comment]
From xenial and forward.

**Comment by MatthijsBurgh** [comment]
I think the `gazebo` target could still depend on `gazebo-setup`. But it is good to fix the naming of system package.

**Comment by Rayman** [comment]
I've reinstated the gazebo-setup target. I've not added it to the dependency of gazebo because gazebo can already be installed with the ros sources. I think gazebo-setup was used when gazebo was not yet released there (around 1204)

**Comment by MatthijsBurgh** [comment]
@Rayman I have reverted the removal of `gazebo-setup` dep. I would like to keep it here, as we use gazebo for HERO. Toyota prescribes to use the gazebo ppa version, so I would like to follow that.

This changes not very much, it just provides you with a little bit of a newer version.
```
apt-cache policy gazebo9
gazebo9:
  Installed: 9.13.0-1~bionic
  Candidate: 9.13.0-1~bionic
  Version table:
 *** 9.13.0-1~bionic 500
        500 http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     9.0.0+dfsg5-3ubuntu1+ppa2 500
        500 http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages
     9.0.0+dfsg5-3ubuntu1 500
        500 http://nl.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Comment by Rayman** [comment]
Ah ok, I didn't know about hero

**Pull request merged**
