### PR TITLE
[gtest] new target

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Should fix CI of https://github.com/tue-robotics/geolib2/pull/34

### CODE REVIEW

**Comment by PetervDooren** [comment]
Shouldnt we specify somewhere that CI needs to install gtest or does it automatically install all tue-env-targets.
And should we add gtest to the hero targets?

**Comment by MatthijsBurgh** [comment]
It is a dependency of geolib, which didn't exist. Cant show the log anymore as I restarted it, after adding this.

**Comment by PetervDooren** [comment]
I understand now. Very well 👍

**Comment by reinzor** [comment]
FYI, `gtest` is included in `catkin`: http://wiki.ros.org/gtest#Building_and_running_tests

**Pull request merged**
